# -*- coding: utf-8 -*-
"""Introdução a Data Science.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FJ3v99oLDLVV-piNSlVP-UgJbhu8cvnT

#Analizando as notas em geral
"""

import pandas as pd
notas = pd.read_csv('ratings.csv')
notas.head()

notas.shape

notas.columns = ['usuarioId','filmeId', 'nota', 'momento']
notas.head()

notas['nota'].unique()

notas['nota'].value_counts()

print('Media', notas.nota.mean())
print('Mediana', notas.nota.median())

notas.nota.head()

notas.nota.plot(kind = 'hist')

notas.nota.describe()

import seaborn as sns

sns.boxplot(notas.nota)

"""#Olhando os fimes"""

filmes = pd.read_csv('movies.csv')
filmes.columns = ['filmeId','titulo','generos']
filmes.head()

notas.head

"""#Analizando algumas notas especificas por filme"""

notas.query('filmeId==1').nota.mean()

notas.query('filmeId==2').nota.mean()

medias_por_filme = notas.groupby('filmeId').mean().nota
medias_por_filme.head()

medias_por_filme.plot(kind = 'hist')

import matplotlib.pyplot as plt

plt.figure(figsize = (5,8))
sns.boxplot(y = medias_por_filme)

medias_por_filme.describe()

sns.distplot(medias_por_filme, bins = 10)

plt.hist(medias_por_filme)
plt.title('Histograma das medias dos filmes')

tmdb = pd.read_csv('tmdb_5000_movies.csv')
tmdb.head()

tmdb.original_language.unique()

contagem_de_linguas = tmdb["original_language"].value_counts().to_frame().reset_index()
contagem_de_linguas.columns = ["original_language","Total"]
contagem_de_linguas.head()

import seaborn as sns
import matplotlib.pyplot as plt
sns.barplot(x="original_language",y= "Total", data = contagem_de_linguas)

sns.catplot(x = "original_language", kind = "count", data = tmdb)

plt.pie(contagem_de_linguas["Total"], labels = contagem_de_linguas["original_language"])

total_lingua = tmdb["original_language"].value_counts()
total_lingua.loc["en"]
total_geral = total_lingua.sum()
total_ingles = total_lingua.loc["en"]
total_resto = total_geral - total_ingles
print(total_resto, total_ingles)

#Criando o DataFrame com as informações extraidas acima
dados = {
    'lingua' : ['ingles', 'outros'],
    'total' : [total_ingles, total_resto]
}

pd.DataFrame(dados)
dados
#Comparando inglês com as outras linguas, com barplot
sns.barplot(data = dados, x ='lingua', y = 'total')

oders_lan = tmdb.query("original_language != 'en'" )
oders_lan
oders_lan_list = tmdb.query("original_language != 'en'" ).original_language.value_counts()

sns.catplot(x = "original_language",
            kind = 'count',
            data = oders_lan,
            aspect = 2,
            palette = "GnBu_d",
            order = oders_lan_list.index)

filmes.head(2)